### ISSUE TITLE
"Mailspring is offline" message continuously displayed

### ISSUE THREAD

**Issue by Amain** [notpushkin/Mailspring-Libre#14]
After opening Mailspring the "Mailspring is offline" message remains visible all the time, even though receiving and sending mail, etc, works just fine. I assume this is related to the central server / login functionality. Obviously it be great to have the message removed :-)

OS: Linux
Version: 1.7.2-libre1 (RPM)

_On a side note: thanks for creating a 'libre' version of the great Mailspring app. I've been waiting for many years for a better alternative open source Linux desktop e-mail client. This might be it!_

**Comment by notpushkin** [comment]
Thank you so much for taking time to try it out!

I've never had this issue, but I believe it should be fixed as of b1d6581. Any chance you could try out the latest `master` build ([rpm] and – just in case – [deb])?

[rpm]: https://files.catbox.moe/ubki5p.rpm
[deb]: https://files.catbox.moe/0ij41p.deb

**Comment by Amain** [comment]
No problem...it's the least I can do. I tested the RPM and it looks like this works; the message isn't displayed anymore. Thanks!

**Comment by Amain** [comment]
FYI: sending mail with the above RPM doesn't work. On the console the following message is seen:

```
22575 [2020-03-03 16:11:41.941] [foreground] [critical]
 ***
 *** A JSON exception occurred during program execution:
 *** [json.exception.type_error.302] type must be boolean, but is null
 ***

22575 [2020-03-03 16:11:41.959] [foreground] [critical]  *** Stack trace (line numbers are approximate):
 *** (unknown)  clone
 ***

```
After switch back to 1.7.2-libre1 release, sending mail works.
