### ISSUE TITLE
Update manager connects to updates.getmailspring.com

### ISSUE THREAD

**Issue by notpushkin** [notpushkin/Mailspring-Libre#15]
https://github.com/notpushkin/Mailspring-Libre/blob/590a746b1ac674c81ea43bf352213362436d7493/app/src/browser/autoupdate-manager.ts#L52-L55

**Comment by notpushkin** [comment]
Fixed in 3cfb1e810be313ac0ced38ea62347446216f67c4. The server doesn't respond with any proper response yet but that can be fixed.

**Comment by keunes** [comment]
@notpushkin I just installed MSL on my dad's machine. Because he's not very tech-savvy, it would be great if the 'update software' button in the programme would work :)
