### ISSUE TITLE
Problem when using the new add account (like thunderbird)

### ISSUE THREAD

**Issue by lefred** [notpushkin/Mailspring-Libre#17]
I've used the last travis build to test.
When I try to add a normal account (imap/stmp) I've an issue related to the smtp:
![Selection_128](https://user-images.githubusercontent.com/609675/75452811-2f6cec00-5973-11ea-9092-28853528565c.png)
I need to allow insecure SSL (was not needed with the previous way to add accounts).
And when I try to check the settings by clicking on "Update Connection Settings..." in Accounts, I've a blank popup that I'm not able to close.

**Comment by lefred** [comment]
It seems that I need to check and un-check both boxes (Allow insecure SSL) and it works

**Comment by lefred** [comment]
However with yet another imap/smtp private account, I'm not able to setup the account:
imap/993/ssl/tls and smtp/465/ssl/tls

The error in the log is:
 ```
Waiting for Account JSON:

Waiting for Identity JSON:
  info: Identity created at 1579887685 - using ID Schema 1
critical: 
 ***
 *** A JSON exception occurred during program execution: 
 *** [json.exception.type_error.302] type must be string, but is null
 ***

critical: 
 ***
 *** A JSON exception occurred during program execution: 
 *** [json.exception.type_error.302] type must be string, but is null
 ***

critical:  *** Stack trace (line numbers are approximate):
 *** ??:?  void nlohmann::detail::from_json(nlohmann::basic_json const&, nlohmann::basic_json::string_t&)
 *** ??:?  decltype ((from_json({parm#1}, {parm#2})),((void)())) nlohmann::detail::from_json_fn::operator()(nlohmann::basic_json const&, string&) const
 *** ??:?  decltype ((nlohmann::(anonymous namespace)::from_json((forward)({parm#1}), {parm#2})),((void)())) nlohmann::adl_serializer::from_json(nlohmann::basic_json const&, string&)
 *** ??:?  string nlohmann::basic_json::get() const
 *** ??:?  Account::SMTPSecurity()
 *** ??:?  MailUtils::configureSessionForAccount(mailcore::SMTPSession&, shared_ptr)
 *** ??:?  runTestAuth(shared_ptr)
 *** ??:?  main
 ***

critical:  *** Stack trace (line numbers are approximate):
 *** ??:?  void nlohmann::detail::from_json(nlohmann::basic_json const&, nlohmann::basic_json::string_t&)
 *** ??:?  decltype ((from_json({parm#1}, {parm#2})),((void)())) nlohmann::detail::from_json_fn::operator()(nlohmann::basic_json const&, string&) const
 *** ??:?  decltype ((nlohmann::(anonymous namespace)::from_json((forward)({parm#1}), {parm#2})),((void)())) nlohmann::adl_serializer::from_json(nlohmann::basic_json const&, string&)
 *** ??:?  string nlohmann::basic_json::get() const
 *** ??:?  Account::SMTPSecurity()
 *** ??:?  MailUtils::configureSessionForAccount(mailcore::SMTPSession&, shared_ptr)
 *** ??:?  runTestAuth(shared_ptr)
 *** ??:?  main
 ***

/usr/share/mailspring/resources/app.asar.unpacked/mailsync: line 4: 826596 Aborted                 (core dumped) SASL_PATH="$(dirname $(realpath $0))" LD_LIBRARY_PATH="$(dirname $(realpath $0));$LD_LIBRARY_PATH" "$(dirname $0)/mailsync.bin" "$@"
```

**Comment by notpushkin** [comment]
> Waiting for Identity JSON:

Wow, mailsync tracebacks are rather unhelpful.

I guess it has to do with the way I “simplified” identity JSON (the id.getmailspring.com account stub) injection, but it worked for me yesterday. I'll look into both issues, thank you!

**Comment by notpushkin** [comment]
My bad – I got carried so much away with autoconfig stuff that I totally forgot to try it on a host that doesn't support it! Should be fixed in 3c26fa53e – could you try it out when it builds?

UPD: [rpm](https://files.catbox.moe/bg47im.rpm), [deb](https://files.catbox.moe/zusukm.deb)

**Comment by lefred** [comment]
Hi, I tested it, adding an account works perfectly this time ! \o/ However I cannot check the settings using "Update Connection Settings..", first time the button doesn't do anything and the second time a blank popup is displayed.

**Comment by notpushkin** [comment]
Yeah, I've noticed that too → #19 
I'll give it some more thought tomorrow, for now the workaround would be to just recreate the account.
