### ISSUE TITLE
Add CI support for Windows and macOS

### ISSUE THREAD

**Issue by notpushkin** [notpushkin/Mailspring-Libre#2]
With a few tweaks to `.travis.yml` we can bring back continuous Linux / Mac builds and push them to GitHub Releases.

- [ ] Linux
  - [x] deb, rpm
  - [ ] deb, rpm repos
  - [x] AUR
  - [ ] Flatpak, AppImage
- [x] macOS
- [x] Windows
- [ ] Publish stable releases to the GitHub Releases tab

**Comment by exprez135** [comment]
Do we plan to wait until we have everything done (Flatpak, AppImage, repository stuff) to push a new pre-release with MacOS and Windows binaries? Or can we do that now?
