### ISSUE TITLE
Add AUR or snap packages

### ISSUE THREAD

**Issue by leobel96** [notpushkin/Mailspring-Libre#22]
I use Manjaro Linux (an Arch linux based distro) and having to manually convert .deb packages is very unconfortable. Could you please also provide AUR packages? Otherwise, why don't you provide snap packages (https://snapcraft.io/)?

**Comment by notpushkin** [comment]
Hey, thanks for trying it out! AUR packaging is welcome, but I'm not an Arch user myself so PRs are welcome! Snap packaging is lower priority as I find these broken every time I decide to try something out, but Flatpak and/or AppImage are something I would like to try out once the app itself stabilizes a bit.

**Comment by Panzki** [comment]
I just created an AUR package, it can be found [here](https://aur.archlinux.org/packages/mailspring-libre/). Since this is the first AUR package I published, I'm not sure that everything is correct. However I tried to install the package on a fresh manjaro and it worked. If you have any problems feel free to contact me either in GitHub or AUR.

**Comment by notpushkin** [comment]
Thank you so much @Panzki! I've added the link to README and release notes.

@leobel96 Please check this out and if it works for you let's close the issue :)

**Comment by leobel96** [comment]
@Panzki Thank you! It works flawlessly!

**Comment by datumbox** [comment]
It would be awesome if you could offer a snap version. Email is exposed to attacks so using the sandboxing capabilities of snap will increase security. Hope that you will offer this option soon. :)

**Comment by isgursoy** [comment]
Snap's sandboxing sucks in my opinion.

**Comment by notpushkin** [comment]
I've been playing around with Flatpak yesterday and got it working, might publish after polishing.

**Comment by datumbox** [comment]
@notpushkin I understand that supporting multiple packages is a pain but it might be worth considering Snaps. The [Mailspring client](https://snapcraft.io/mailspring) is available as Snap and is prominently featured on the Snap store. Offering this libre fork as well could give great exposure to your project. :)

**Comment by notpushkin** [comment]
@datumbox I'd be happy to put it up in readme and release notes if you take some time and submit it to Snapcraft :) I don't use Snap, and I don't like it personally so I don't think I can help with that.

There's two main reasons behind my decision. The first is that GTK was badly broken for me when I tested it in Snap a while ago, but a more important one is the fact that Snapcraft is centralized and controlled by Canonical directly. You can set up a separate repo but only one can be configured per system [[1](https://github.com/AppImage/AppImageKit/wiki/Similar-projects#application-distribution), [2](https://medium.com/nitrux/nitrux-appimage-52937e286edc)].  Despite my love for Canonical and belief that this decision was made in good faith, I can't support such kind of lock-in.

**Comment by alexanderadam** [comment]
I creating [a request thread in the snapcraft forum](https://forum.snapcraft.io/t/mailspring-libre/22337) in case anyone is interested in that.
