### ISSUE TITLE
Can't add G Suite accounts

### ISSUE THREAD

**Issue by notpushkin** [notpushkin/Mailspring-Libre#23]
We're now choosing whether to use Google OAuth or username/password auth based on the domain name (only `@gmail.com` gets OAuth). We should check MX records too, so that G Suite (GMail on custom domain) accounts get the same auth flow.

Workaround: allow “[less secure apps](https://myaccount.google.com/u/1/lesssecureapps)” to log in using password.

**Comment by exprez135** [comment]
We now have the Gmail/G Suite option which mostly simplifies this. I've tested and it works fine with an app password. Is there anything else we want to do with this?

**Comment by notpushkin** [comment]
Should be fine as it is now I believe!
