### ISSUE TITLE
Donation / Financial support

### ISSUE THREAD

**Issue by cdorin93** [notpushkin/Mailspring-Libre#27]
I recently stumbled upon your fork and I must say that it looks very interesting! Since I am not really a developer, I would love to contribute with donations from time to time to this project (and I assume many others will think the same). Did you have the time to think about that? Thank you for your great work!

**Comment by notpushkin** [comment]
@cdorin93 Thank you so much for considering this!

I don't think I personally deserve any money for this – I hacked it together over a few evenings, and the few things that are left (most importantly, open source rewrite of the sync engine) I think I'm not yet ready to handle. Perhaps for now, assigning bounties (using something like [BountySource](https://www.bountysource.com/) – which is down right now but hopefully goes back up soon) to the tickets left would be the best way.

You should also consider finding a way to support the original maintainer, [\@bengotow](https://github.com/bengotow), who did awesome work up there.

<details>
<summary>That said, if you really want to give me a few bucks, feel free to :)</summary>
Name: Alexander Pushkov<br>
IBAN: DE25100110012620853325<br>
BIC: NTSBDEB1XXX

or https://buymeacoff.ee/ale
</details>

**Comment by notpushkin** [comment]
And in longer perspective, perhaps something like [Open Collective](https://opencollective.com/) would work? Or maybe any other ideas?

**Comment by exprez135** [comment]
@notpushkin If the intention is, at some point, to notarize releases with Apple for macOS, someone will need a Developer ID which costs $99. Unless you already have one? In any case, for the longer perspective, something like Open Collective sounds like a great idea.

**Comment by ijann** [comment]
I would recommend you to create your own fork of mailspring,
so you don't have to be hacking or breaking the app,
in the end mailspring is a nylas fork,
you should give it a proper name and
have your own brand,
being this fork without telemetry and free without limits,
financing yourself with Open Collective as you mentioned,
somewhat legal and little intrusive with mailspring.

but it is important that it be without telemetry and without limits of characteristics ;D  please

**Comment by notpushkin** [comment]
@ijann Would love to, but we can't: the sync engine is proprietary and can only be used [with applications named “Mailspring”](https://github.com/notpushkin/Mailspring-Libre/blob/master/LICENSE-mailsync.md) :')

**Comment by ijann** [comment]
I get it,
what a pity

**Comment by teon** [comment]
I would also like to back the project - so that you would have time to work on it. I have been waiting for year for a mail client like Mailspring. It's a schame that they only support the server dependency.
What you have done is just plain awesome! and I've been waiting for this "fork" for sime time. Thank you!

BTW - there is github sponsors now...

**Comment by ccrvlh** [comment]
@notpushkin honest question: what is the big deal about the sync engine? don't get me wrong, I imagine it can be really complex, but how complex to use Nylas for example, and Mailspring fork just as the frontend?

**Comment by notpushkin** [comment]
@lowercase00 The sync engine [is now open source, actually](https://community.getmailspring.com/t/a-free-open-source-future-for-mailspring/484). And now that upstream Mailspring also doesn't require ID to function, I don't really have a reason to keep the fork. (Okay, one possible reason could be enabling some Pro features back without payment, but while technically legal, that's just not something I want to maintain :-)
