### ISSUE TITLE
Instructions for build ?

### ISSUE THREAD

**Issue by raphaeljolivet** [notpushkin/Mailspring-Libre#3]
I tried "npm install" but got the following error :

```
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 5.3.0-26-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/raph/Mailspring-Libre-master/app/node_modules/keytar
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keytar@4.3.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
```

Could you please provide minimum build / install instructions ?

**Comment by alexanderadam** [comment]
~~IMHO `npm install` and [`npm run build`](https://github.com/notpushkin/Mailspring-Libre/blob/master/package.json#L101) should be enough.~~

**EDIT:** See [**notpushkin**'s comment](https://github.com/notpushkin/Mailspring-Libre/issues/3#issuecomment-579648622) below.

I don't know what's the problem in your case, but there are [various solutions on stackoverflow](https://duckduckgo.com/?q=%2B%22npm+ERR!+code+ELIFECYCLE%22+site%3Astackoverflow.com&t=h_&ia=web) (i.e. [here](https://stackoverflow.com/questions/42308879/npm-err-code-elifecycle#answers-header)) for your issue.
I guess it wouldn't help if I would just repeat what others wrote, so I guess it would be easier if you check for yourself what's helping and then keep this issue updated when you found the solution.

**Comment by notpushkin** [comment]
Mailspring needs to compile a few native modules, so you have to have the libraries headers installed on Linux. There's already a guide in CONTRIBUTING.md – follow [this section](https://github.com/notpushkin/Mailspring-Libre/blob/master/CONTRIBUTING.md#build-and-run-from-source) :)

(Perhaps we should add a link to it in README too, for greater visibility)
