### ISSUE TITLE
Prevent public IP queries done from "is-online"

### ISSUE THREAD

**Issue by und3rd09** [notpushkin/Mailspring-Libre#32]
Hi,

first many thanks for providing this project! I'm loving this mail client but i didn't want to create a useless account so found your project, nice work!

On a WireShark debugging session i discovered that some weird recurring DNS queries were sent from my machine (Debian) that i could not explain:
![image](https://user-images.githubusercontent.com/64483330/80501117-59d92680-896f-11ea-8095-455517d90868.png)

After a research i discovered that MailSpring is using a library for online detection (https://github.com/sindresorhus/is-online) and this library is responsible for the requests.

See https://github.com/Foundry376/Mailspring/issues/660

Is it possible to prevent this? Im not feeling well with leaking my IP to these companies...

Greetings!

**Comment by exprez135** [comment]
Thanks for the report! With the latest release we've pulled in a fix for this from upstream (7c0cb4e6fc69a34bd22d10764ceb7a9dc73726a1). Mailspring should now use the connection to your mail servers instead of is-online or DNS. Let us know if you catch anything else sniffing around!
