### ISSUE TITLE
Upstream update?

### ISSUE THREAD

**Issue by ghost** [notpushkin/Mailspring-Libre#33]
Hello,

Any chance to get an upstream update?

Upstream mailspring solved important issues, like yahoo authentication not working anymore.

Thanks for your work. Love the idea of your fork.

**Comment by exprez135** [comment]
This should be underway soon!

**Comment by alexanderadam** [comment]
![An update to Mailspring is available (1.7.8-13635bcf)](https://user-images.githubusercontent.com/372620/89272722-d8b0c000-d63e-11ea-9a74-58e18589d672.png)

Apart from that, the build still seems to look for the original repository releases instead Mailspring-Libre releases.
