### ISSUE TITLE
Errors installing on windows

### ISSUE THREAD

**Issue by fmiqbal** [notpushkin/Mailspring-Libre#36]
Windows and MacOS build have actually already been added to travis, just not yet to releases. Travis upload them to catbox.moe when done.

Latest Windows:
https://files.catbox.moe/wn3rbc.msi

Latest MacOs:
https://files.catbox.moe/6o27qn.zip

_Originally posted by @louis-lau in https://github.com/notpushkin/Mailspring-Libre/issues/1#issuecomment-640226934_

I got this while installing

![image](https://user-images.githubusercontent.com/8409391/84182027-f553d000-aab3-11ea-9ad1-f745467f3064.png)

[log1.log](https://github.com/notpushkin/Mailspring-Libre/files/4753860/log1.log)
[log2.log](https://github.com/notpushkin/Mailspring-Libre/files/4753863/log2.log)

**Comment by notpushkin** [comment]
Thanks for reporting this! Will take a more thorough look when I can. On a glance, https://github.com/JoshuaWise/better-sqlite3/issues/227 might be related.

**Comment by bliet** [comment]
Same bug in 1.7.8. Any plans to fix this?

**Comment by exprez135** [comment]
> Same bug in 1.7.8. Any plans to fix this?

Yes! This is the next thing on my TODO list. I need to get familiar with the problem and investigate thoroughly. As soon as there's a fix we'll make sure to get it out. Sorry for the trouble.
If anyone has any ideas, please let me know!

**Comment by exprez135** [comment]
Have a lead, and have a build which works on my end. If anyone can test: https://ci.appveyor.com/api/buildjobs/26ncloqje2udqifd/artifacts/MailspringSetup.exe

It appears that Travis is not properly rebuilding some modules which require native dependencies. AppVeyor does do this. If I can't get Travis to work properly we can hook AppVeyor to the repository and use Windows builds from there.

**Comment by louis-lau** [comment]
I initially submitted a working PR which used appveyor. But then someone moved it to Travis. So we could just revert that if it solves this issue.

**Comment by exprez135** [comment]
That would be me 🤦 
I think I've actually gotten Travis to work now. It's all a caching problem. I'm going to test the new build and update the release with new files tonight.

**Comment by exprez135** [comment]
Update: I was wrong. Travis rebuilt everything but I encountered the same error. I've just pushed .appveyor.yml back into the repo (thank you @louis-lau!).

@notpushkin is it possible for us to set up an AppVeyor project for the repo?

I've just updated the release files with functioning Windows 1.7.8 builds.

**Comment by notpushkin** [comment]
@exprez135 IIRC AppVeyor didn't work for me (it did work for @louis-lau though, so that's weird). I'll give it one more try tonight and let you know if it works!

**Comment by notpushkin** [comment]
Looks like we're good to go!

[![Windows build status](https://img.shields.io/appveyor/build/notpushkin/Mailspring-Libre/master?label=windows)](https://ci.appveyor.com/project/notpushkin/mailspring-libre)

**Comment by exprez135** [comment]
Awesome! Thank you!
