### ISSUE TITLE
Remove nag screen when adding more than four accounts

### ISSUE THREAD

**Issue by alexanderadam** [notpushkin/Mailspring-Libre#39]
When adding more than four accounts, this message appears:

![You're syncing more than four accounts — please consider paying for Mailspring Pro! Manage | Dismiss](https://user-images.githubusercontent.com/372620/92012204-71c11c80-ed4c-11ea-8a76-424d0a44d9c5.png)

So I guess this screen and the check for it can be removed?

**Comment by exprez135** [comment]
Working on this to be included in the next update!
