### ISSUE TITLE
Bug: deb installation - dependency on outdated gvfs-bin

### ISSUE THREAD

**Issue by rjl6789** [notpushkin/Mailspring-Libre#45]
( mailspring-1.7.8-libre-amd64.deb - installing on ubuntu groovy)

This is an install issue. Similar to atom/atom#21494 the deb file has a dependency on gvfs-bin:

> gvfs-bin is an old outdated transitional package, Debian removed it in this upload and Ubuntu followed up
https://packages.qa.debian.org/g/gvfs/news/20200910T003354Z.html

The "official" mailspring deb seems to install ok though.  I'm looking forward to trying mailspring-libre though once this issue is sorted.

Thanks

**Comment by rjl6789** [comment]
btw thanks for this - with the information you provided in your pull I unpacked your existing deb file and modified the control file, packaged back up and bobs your uncle - Mailspring-libre.  Cheers!!

**Comment by etchtoolkit** [comment]
I confirm the issue. Tried to install both 1.7.8 and 1.7.2 with the same error. Is there a quick way to fix this ? Cheers !

**Comment by rjl6789** [comment]
Yep - see my comment.

I basically (I.e very rough instructions) did:
`ar x thedebfile.deb` produces files, then
`tar xzfv control.tar.gz ` which produces more files including `control `, edit this and fix up dependencies in-line with the pull. Then repack the files that came from the tar (`tar czvf`) and repack the files that came out of the deb ( e.g `ar rcs newpackage.deb debian-binary control.tar.gz data.tar.gz `

**Comment by notpushkin** [comment]
https://u.ale.sh/mailspring-1.7.8-PATCHED-libre-amd64.deb

**Comment by etchtoolkit** [comment]
Thank you for the patch, worked perfectly !
