### ISSUE TITLE
Travis credits ran out *shrug*

### ISSUE THREAD

**Issue by notpushkin** [notpushkin/Mailspring-Libre#47]
> Builds have been temporarily disabled for public repositories due to a negative credit balance.

I've sent an email asking for another 10000 credits [OSS allowance](https://docs.travis-ci.com/user/billing-faq/#what-if-i-am-building-open-source) which should last for around 30 builds – hopefully we can think of something else by then, or I could ask for some more.

**Comment by ForsakenHarmony** [comment]
GitHub Actions do have unlimited minutes for open source projects

**Comment by notpushkin** [comment]
@ForsakenHarmony Thank you for the suggestion! In fact, I've played around with using GitHub Actions to run builds for this project (around the same time I've been trying porting commits from here to [AST patches](https://github.com/Mailspring-Libre/next/blob/master/patches/10-identity-replace.js)). I haven't quite got there and now that the upstream Mailspring is both FLOSS and [not dependent on central server](https://github.com/Foundry376/Mailspring/pull/2288) this project actually doesn't serve its original purpose (at this point at least :-) things might change in future)
