### ISSUE TITLE
Bug: Google authentication doen't work

### ISSUE THREAD

**Issue by zeromask1337** [notpushkin/Mailspring-Libre#48]
**Description**
When I try to log into Gmail (after installation) app gives me error

```
----------IMAP----------
connect <mailcore::IMAPSession:006FF668>
* OK Gimap ready for requests from 46.138.51.115 i3mb15800739ljg
ssl connect imap.gmail.com 993 2
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
1 CAPABILITY
* CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER AUTH=XOAUTH
1 OK Thats all she wrote! i3mb15800739ljg
connect ok
login
2 LOGIN "vysmol@gmail.com" *********
2 NO [AUTHENTICATIONFAILED] Invalid credentials (Failure)
```

**To Reproduce**
1. Open Mailspring
2. Click on 'Gmail or G Suite'
3. Enter your data

**Expected behavior**
Authentication successful

**Screenshots**
![изображение](https://user-images.githubusercontent.com/22420621/106596419-07641080-6566-11eb-937e-272451b361dc.png)

**Setup:**
 - OS: Windows 10
 - OS Version 2004 (19041.746)
 - Mailspring Version: ex: 1.7.8

**Comment by notpushkin** [comment]
Related: #23, #49.

**Comment by keunes** [comment]
I downloaded and installed 1.7.8 (libre obv, on Windows) on my dad's machine, and was seeing the same error. Enabling less secured apps (as suggested in #23) solved the problem.

However, in #23 @notpushkin you say it should be fixed. Will it be solved in an upcoming version? Or did I not understand your comment correctly?

Thanks anyway for working on this!
