### ISSUE TITLE
Please mark repository as "archived"

### ISSUE THREAD

**Issue by alerque** [notpushkin/Mailspring-Libre#52]
If development work is discontinued as the README suggests, please mark it as status Archived in GitHub. This would be a better signal to distro packagers (I'm here researching whether or not to accept a deletion request for Arch packaging).

**Comment by notpushkin** [comment]
Hey @alerque! There are still come discussions going on in Issues, and I personally think it's best to leave it open (if you archive a repo, everything becomes read-only). That said, I believe it should be safe to delete distro packages now. Hope that clears things up a bit!

**Comment by alerque** [comment]
Disto packages deleted.
