### ISSUE TITLE
How do I install this version and not the download versions contained in the readme.md text?

### ISSUE THREAD

**Issue by antonical** [notpushkin/Mailspring-Libre#7]
Hi I downloaded mailspring from the main mailspring site but it required an ID and online registration. 

this fork seemed to suggest I could install mailspring and not require an online ID etc. But  I can't figure out how to install it and could not find any install instructions other than pointing me back to the mailspring site for download.

Probably being dumb here. 

Any help appreciated.

Cheers

**Comment by notpushkin** [comment]
Hi @antonical! Sorry for the mess, we still need to update README among a few other things. There are only Linux builds available now [here](https://github.com/notpushkin/Mailspring-Libre/releases/tag/1.7.2-libre), Windows and macOS are coming up next!

I'll leave this open until we update README in case somebody has similar issue finding the builds.

**Comment by antonical** [comment]
We run Ubuntu 18.04 DT builds so that works.

**Comment by notpushkin** [comment]
Cool! Please don't hesitate to post any issues you run into :)

**Comment by antonical** [comment]
![Screenshot from 2020-02-06 10-56-04](https://user-images.githubusercontent.com/13483395/73930932-5170d280-48cf-11ea-90c4-3ad1ccd6828f.png)
.deb installed fine via software. Does not run correctly I get a number of chrome inspector windows that pop up and a blank config screen that I have to kill to remove it.

![Screenshot from 2020-02-06 10-52-10](https://user-images.githubusercontent.com/13483395/73930722-eaebb480-48ce-11ea-9dd9-3328c518147e.png)

**Comment by antonical** [comment]
Apologies for the delay. This is an upto date 18.04 DT with the HWE Kernel enabled. It runs the normal mailspring install fine and installs via snap or .deb

Not sure what else to tell you. The .deb installs fine via Software and launches from the menu but then does not initialise correctly.

We only use LTS flavours of Ubuntu.

Cheers

**Comment by notpushkin** [comment]
README now points to GitHub Releases, and I've added a link right after the repo description, so I hope it's easier to find now.
